### ISSUE TITLE
Configure Google login

### ISSUE THREAD

**Issue by ghost** [PimpAPP/pimpapp-frontend#4]

**Comment by fernandobalm** [comment]
I could successfully configure it for http://localhost:3000.
Investigating in internet, I noted that can exist some specific questions regarding configuring for subdomains. 
As we intend to use in our own server with our domain I guess this will not be a problem for us.
Anyway, I will confirm that it works for use after installing Meteor in our official server and testing it.

**Comment by fernandobalm** [comment]
I guess I find out the problem.
For some reason, names with underscore are not accepted in Authorized redirect URIs field of Credentials configuration of API Manager of Google Console Developers.
Once that Katrine's uri is https://ui_development.meteor.com/_oauth/google, the problem occurs. If you try https://uidevelopment.meteor.com/_oauth/google it accepts uri's configuration.
I deployed for https://pimp.meteor.com and could configure it successfully.

**Comment by ghost** [comment]
Awesome, Fernando!!

On Mon, Feb 1, 2016 at 8:13 AM Fernando Barreto de Almeida
notifications@github.com wrote:
I guess I find out the problem.
For some reason, names with underscore are not accepted in Authorized redirect
URIs field of Credentials configuration of API Manager of Google Console
Developers.
Once that Katrine's uri is https://ui_development.meteor. com/_oauth/google , the problem occurs. If you try https://uidevelopment.meteor. com/_oauth/google it accepts uri's configuration.
I deployed for https://pimp.meteor.com and could configure it successfully.
